export const INITIAL = 'INITIAL';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const SHOW_LOCAL_LOADER = 'SHOW_LOCAL_LOADER';
export const HIDE_LOCAL_LOADER = 'HIDE_LOCAL_LOADER';
export const SET_MESSAGE = 'SET_MESSAGE';
export const ERROR = 'ERROR';

export const SIGN_SIGNUP = 'SIGN/SIGNUP';
export const SIGN_SIGNIN = 'SIGN/SIGNIN';
export const SIGN_SIGNOUT = 'SIGN/SIGNOUT';
export const SIGN_SIGNIN_ERROR = 'SIGN/SIGNIN_ERROR';
export const SIGN_SIGNUP_CLICK = 'SIGN/SIGNUP_CLICK';
export const SIGN_SIGNIN_CLICK = 'SIGN/SIGNIN_CLICK';
export const SIGN_SIGNOUT_CLICK = 'SIGN/SIGNOUT_CLICK';
export const SIGN_SIGNIN_WITH_TOKEN = 'SIGN/SIGNIN_WITH_TOKEN';
export const PARTNER_SIGNUP = 'PARTNER/SIGNUP';
export const PARNTER_SIGNIN = 'PARTNER/SIGNIN';
export const PARTNER_SIGNOUT = 'PARTNER/SIGNOUT';
export const PARTNER_SIGNUP_CLICK = 'PARTNER/SIGNUP_CLICK';
export const PARTNER_SIGNIN_CLICK = 'PARTNER/SIGNIN_CLICK';
export const PARTNER_SIGNOUT_CLICK = 'PARTNER/SIGNOUT_CLICK';

export const FACILITY_LOAD_FOR_PARTNER = 'FACILITY/LOAD_FOR_PARTNER';
export const FACILITY_LOAD_FOR_PARTNER_LOADING = 'FACILITY/LOAD_FOR_PARTNER_LOADING';
export const FACILITY_CREATE_CLICK = 'FACILITY/CREATE_CLICK';
export const FACILITY_CREATE = 'FACILITY/CREATE';
export const FACILITY_ADD_ROOM_TO_FACILITY_CLICK = 'FACILITY/ADD_ROOMS_TO_FACILITY_CLICK';

export const LOCATION_LOAD_CITY_LOADING = 'LOCATION/LOAD_CITY_LOADING';
export const LOCATION_LOAD_CITY = 'LOCATION/LOAD_CITY';

export const CATALOG_SEARCH_LOCATION_CLICK = 'CATALOG/SEARCH_LOCATION_CLICK';
export const CATALOG_SEARCH_LOCATION = 'CATALOG/SEARCH_LOCATION';
